SMMuseum/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('testapps/', include('testapp.urls')),
    path('sites/', include('siteapp.urls')),
    path('curators/', include('curatorapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

curatorapp/urls.py
from django.urls import path

from curatorapp.views import BibleDetailView, BibleListView, PermanentDetailView, PermanentListView, SpecialDetailView, SpecialListView

app_name = "curatorapp"

urlpatterns = [
    # 작품 리스트
    path('permanent_list/', PermanentListView.as_view(), name='permanent_list'),
    path('bible_list/', BibleListView.as_view(), name='bible_list'),
    path('special_list/', SpecialListView.as_view(), name='special_list'),
    # 작품 설명
    path('permanent_detail/<int:pk>', PermanentDetailView.as_view(), name='permanent_detail'),
    path('bible_detail/<int:pk>', BibleDetailView.as_view(), name='bible_detail'),
    path('special_detail/<int:pk>', SpecialDetailView.as_view(), name='special_detail'),
]

siteapp/urls.py
from django.urls import path

from siteapp.views import GroupView, GuideDonationView, GuideFacilityView, GuideWatchView, IntroductionHistoryView, MainView, HelloView, RouteView

app_name = "siteapp"

urlpatterns = [
    # 소개
    path('history/', IntroductionHistoryView, name='history'),
    path('main/', MainView, name='main'),
    path('hello/', HelloView, name='hello'),
    path('group/', GroupView, name='group'),
    path('route/', RouteView, name='route'),
    # 안내
    path('guide_facility/', GuideFacilityView, name='guide_facility'),
    path('guide_donation/', GuideDonationView, name='guide_donation'),
    path('guide_watch/', GuideWatchView, name='guide_watch'),
]

testapp/urls.py
from django.urls import path

from testapp.views import TestOCRCreateView, TestOCRDetailView

app_name = "testapp"

urlpatterns = [
    path('create/', TestOCRCreateView.as_view(), name='create'),
    path('detail/<int:pk>', TestOCRDetailView.as_view(), name='detail'),
]

curatorapp/models.py
from django.db import models

from curatorapp.validators import validate_file_extension


# Create your models here.
# 상설전시관
class Permanent(models.Model):
    title = models.CharField(max_length=30, null=False)
    image = models.ImageField(upload_to='permanent/img/', null=False)
    content = models.TextField(null=True)
    mp3 = models.FileField(upload_to='permanent/mp3/', validators=[validate_file_extension])

# 성서전시관
class Bible(models.Model):
    title = models.CharField(max_length=30, null=False)
    image = models.ImageField(upload_to='bible/img/', null=False)
    content = models.TextField(null=True)
    mp3 = models.FileField(upload_to='bible/mp3/', validators=[validate_file_extension])

# 특별전시관
class Special(models.Model):
    title = models.CharField(max_length=30, null=False)
    image = models.ImageField(upload_to='special/img/', null=False)
    content = models.TextField(null=True)
    mp3 = models.FileField(upload_to='special/mp3/', validators=[validate_file_extension])

siteapp/models.py
from django.db import models

# Create your models here.
class Introduction_history(models.Model):
    date = models.CharField(max_length=20, null=False)
    content = models.TextField(null=False)

testapp/models.py
from django.db import models

# Create your models here.
class TestOCR(models.Model):
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='test/', null=False)

testapp/forms.py
from django.forms import ModelForm

from testapp.models import TestOCR


class TestCreationForm(ModelForm):
    class Meta:
        model = TestOCR
        fields = ['title', 'image']

curatorapp/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from curatorapp.models import Bible, Permanent, Special

# Create your views here.
# 작품 리스트
class PermanentListView(ListView):
    model = Permanent
    context_object_name = 'permanent_list'
    template_name = 'curatorapp/permanent_list.html'
    paginate_by = 8


class BibleListView(ListView):
    model = Bible
    context_object_name = 'bible_list'
    template_name = 'curatorapp/bible_list.html'
    paginate_by = 8


class SpecialListView(ListView):
    model = Special
    context_object_name = 'special_list'
    template_name = 'curatorapp/special_list.html'
    paginate_by = 8


# 작품 설명
class PermanentDetailView(DetailView):
    model = Permanent
    context_object_name = 'target_permanent'
    template_name = 'curatorapp/permanent_detail.html'


class BibleDetailView(DetailView):
    model = Bible
    context_object_name = 'target_bible'
    template_name = 'curatorapp/bible_detail.html'


class SpecialDetailView(DetailView):
    model = Special
    context_object_name = 'target_special'
    template_name = 'curatorapp/special_detail.html'

siteapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from SMMuseum.settings import deploy

from siteapp.models import Introduction_history


# Create your views here.
def IntroductionHistoryView(request):
    history = Introduction_history.objects
    template = loader.get_template('siteapp/history.html')
    context = {
        'history': history,
    }
    return HttpResponse(template.render(context, request))

def MainView(request):
    return render(request, 'siteapp/main.html')

def HelloView(request):
    return render(request, 'siteapp/hello.html')

def GroupView(request):
    return render(request, 'siteapp/group.html')

def RouteView(request):
    template = loader.get_template('siteapp/route.html')
    context = {
        'api_key': deploy.KAKAO_MAP_API_KEY
    }
    return HttpResponse(template.render(context, request))

def GuideFacilityView(request):
    return render(request, 'siteapp/guide_facility.html')

def GuideDonationView(request):
    return render(request, 'siteapp/guide_donation.html')

def GuideWatchView(request):
    return render(request, 'siteapp/guide_watch.html')

testapp/views.py
from django.shortcuts import render
from django.urls import reverse

from django.views.generic import CreateView, DetailView
from testapp.forms import TestCreationForm

from testapp.models import TestOCR


# Create your views here.
class TestOCRCreateView(CreateView):
    model = TestOCR
    context_object_name = 'target_info'
    form_class = TestCreationForm
    template_name = 'testapp/create.html'
    
    def get_success_url(self):
        return reverse('testapp:detail', kwargs={'pk': self.object.pk})


class TestOCRDetailView(DetailView):
    model = TestOCR
    context_object_name = 'target_info'
    template_name = 'testapp/detail.html'

curatorapp/templates/curatorapp/bible_detail.html
{% extends 'base.html' %}


{% block content %}

<style>
    body {
      background-color: #F7FCFE;
    }

    a {
        text-decoration: none;
        color: black;
    }

    img {
        width: 70%; 
        border-radius: 1rem; 
        margin: 2rem 0;
    }

    h1 {
        margin: 5rem auto;
        text-align: center;
        font-size: 10vw;
    }

    h3 {
        margin: 3rem auto;
        text-align: center;
        font-size: 6vw;
    }

    audio {
        margin: 3rem auto;
    }

</style>

<div style="text-align: center;">
    <div>
        <a href="{% url 'curatorapp:bible_list' %}">
            <h1>
                성서전시실
            </h1>
        </a>

        <img src="{{ target_bible.image.url }}" alt="">
    </div>
    
    <div>
        <h3> {{target_bible.title}} </h3>
        <p style="text-align: left; font-size: 3vw; margin-top: 3rem;">
            {{target_bible.content }}
        </p>
    </div>

    <div>
        <audio controls>
            <source src="{{ target_bible.mp3.url }}" type="audio/mp3">
            해당 브라우저는 Audio 지원이 되지 않습니다!
            </audio>
    </div>
</div>
{% endblock %}

curatorapp/templates/curatorapp/bible_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>

    body {
      background-color: #F7FCFE;
    }

    a {
        text-decoration: none;
        color: black;
    }

    h1 {
        margin: 10rem auto;
        text-align: center;
        font-size: 10vw;
    }

    h3 {
        margin: 1rem auto;
        text-align: center;
        font-size: 3vw;
    }

    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        width: 250px;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img{
        width: 100%;
        border-radius: 2rem;
    }

</style>

<h1 style="text-align: center; font-size: 6vw;">
    성서전시실
</h1>

<div style="margin: 5rem auto;">
    {% if permanent_list %}
    <div class="container">
        {% for permanent in permanent_list %}
        <a href="{% url 'curatorapp:bible_detail' pk=permanent.pk %}">
            {% include 'snippets/card.html' with permanent=permanent %}
            <h3>
                {{ permanent.title }}
            </h3>
        </a>
        {% endfor %}
    </div>
    <script src="{% static 'SMMuseum/js/magic_grid.js' %}"></script>
    {% else %}
    <div style="text-align: center;">
        <h1>작품을 올려주세요!</h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination_permanent.html' with page_obj=page_obj %}
</div>

{% endblock %}

curatorapp/templates/curatorapp/permanent_detail.html
{% extends 'base.html' %}


{% block content %}

<style>
    body {
      background-color: #F7FCFE;
    }

    a {
        text-decoration: none;
        color: black;
    }

    img {
        width: 60%; 
        border-radius: 1rem; 
        margin: 2rem 0;
    }

    h1 {
        margin-top: 10rem;
        text-align: center;
        font-size: 10vw;
    }

    h3 {
        margin: 3rem auto;
        text-align: center;
        font-size: 6vw;
    }

    audio {
        margin-bottom: 5rem;
    }

</style>

<div style="text-align: center;">
    <div>
        <a href="{% url 'curatorapp:permanent_list' %}">
            <h1>
                상설전시실
            </h1>
        </a>

        <img style="margin-top: 7rem;" src="{{ target_permanent.image.url }}" alt="">
    </div>
    
    <div>
        <h3> {{target_permanent.title}} </h3>
        <p style="text-align: left; font-size: 3vw; margin: 5rem auto;">
            {{target_permanent.content }}
        </p>
    </div>

    <div>
        <audio controls>
            <source src="{{ target_permanent.mp3.url }}" type="audio/mp3">
            해당 브라우저는 Audio 지원이 되지 않습니다!
            </audio>
    </div>
</div>
{% endblock %}

curatorapp/templates/curatorapp/permanent_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>

    body {
      background-color: #F7FCFE;
    }

    a {
        text-decoration: none;
        color: black;
    }

    h1 {
        margin: 10rem auto;
        text-align: center;
        font-size: 10vw;
    }

    h3 {
        margin: 1rem auto;
        text-align: center;
        font-size: 3vw;
    }

    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        width: 270px;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img{
        width: 100%;
        border-radius: 2rem;
    }

</style>

<h1>
    상설전시실
</h1>

<div>
    {% if permanent_list %}
    <div class="container">
        {% for permanent in permanent_list %}
        <a href="{% url 'curatorapp:permanent_detail' pk=permanent.pk %}">
            {% include 'snippets/card.html' with permanent=permanent %}
            <h3>
                {{ permanent.title }}
            </h3>
        </a>
        {% endfor %}
    </div>
    <script src="{% static 'SMMuseum/js/magic_grid.js' %}"></script>
    {% else %}
    <div style="text-align: center;">
        <h1>작품을 올려주세요!</h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination_permanent.html' with page_obj=page_obj %}
</div>

{% endblock %}

curatorapp/templates/curatorapp/special_detail.html
{% extends 'base.html' %}


{% block content %}

<style>
    body {
      background-color: #F7FCFE;
    }

    a {
        text-decoration: none;
        color: black;
    }

    img {
        width: 70%; 
        border-radius: 1rem; 
        margin: 2rem 0;
    }

    h1 {
        margin: 5rem auto;
        text-align: center;
        font-size: 10vw;
    }

    h3 {
        margin: 3rem auto;
        text-align: center;
        font-size: 6vw;
    }

    audio {
        margin: 3rem auto;
    }

</style>

<div style="text-align: center;">
    <div>
        <a href="{% url 'curatorapp:special_list' %}">
            <h1>
                특별전시실
            </h1>
        </a>

        <img src="{{ target_special.image.url }}" alt="">
    </div>
    
    <div>
        <h3> {{target_special.title}} </h3>
        <p style="text-align: left; font-size: 3vw; margin-top: 3rem;">
            {{target_special.content }}
        </p>
    </div>

    <div>
        <audio controls>
            <source src="{{ target_special.mp3.url }}" type="audio/mp3">
            해당 브라우저는 Audio 지원이 되지 않습니다!
            </audio>
    </div>
</div>
{% endblock %}

curatorapp/templates/curatorapp/special_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>

    body {
      background-color: #F7FCFE;
    }

    a {
        text-decoration: none;
        color: black;
    }

    h1 {
        margin: 10rem auto;
        text-align: center;
        font-size: 10vw;
    }

    h3 {
        margin: 1rem auto;
        text-align: center;
        font-size: 3vw;
    }

    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        width: 250px;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img{
        width: 100%;
        border-radius: 2rem;
    }

</style>

<h1 style="text-align: center; font-size: 6vw;">
    특별전시실
</h1>

<div style="margin: 5rem auto;">
    {% if permanent_list %}
    <div class="container">
        {% for permanent in permanent_list %}
        <a href="{% url 'curatorapp:special_detail' pk=permanent.pk %}">
            {% include 'snippets/card.html' with permanent=permanent %}
            <h3>
                {{ permanent.title }}
            </h3>
        </a>
        {% endfor %}
    </div>
    <script src="{% static 'SMMuseum/js/magic_grid.js' %}"></script>
    {% else %}
    <div style="text-align: center;">
        <h1>작품을 올려주세요!</h1>
    </div>
    {% endif %}

    {% include 'snippets/pagination_permanent.html' with page_obj=page_obj %}
</div>

{% endblock %}

siteapp/templates/siteapp/group.html
{% extends 'base.html' %}


{% block content %}

<style>
    body {
      background-color: #F7FCFE;
    }

    h1 {
        margin: 7rem auto;
        text-align: left;
        font-size: 10vw;
    }

    img{
        width: 100%; 
        border-radius: 1rem; 
        margin-bottom: 10rem;
    }
</style>

<div>
    <div>
        <h1>
            조직도
        </h1>

        <img src="https://museum.sunmoon.ac.kr/images/subpage/josikdo.gif" alt="">
    </div>
</div>

{% endblock %}

siteapp/templates/siteapp/guide_donation.html
{% extends 'base.html' %}


{% block content %}

<style>
    body {
      background-color: #F7FCFE;
    }

    h1 {
        margin: 10rem auto;
        text-align: left;
        font-size: 10vw;
    }

    h2 {
        margin-bottom: 3rem;
        text-align: left;
        font-size: 7vw;
    }

    img{
        width: 100%; 
        border-radius: 1rem; 
        margin-bottom: 6rem;
    }
</style>

<div>
    <div>
        <h1>
            기증 안내
        </h1>
    </div>
    <div>
        <img src="https://museum.sunmoon.ac.kr/images/subpage/img-museum01.jpg" alt="">

        <h2>
            문화재 기증 문의처
        </h2>
        <p style="text-align: left; margin-bottom: 10rem; font-size: 2.6vw;">
            문화재 기증에 대해서 문의하실 사항이 있으시면 아래의 연락처로 문의하여 주시기 바랍니다.<br>
            문의처 : 선문대학교 박물관 (전화: 041) 530-2781 )
        </p>
    </div>
</div>

{% endblock %}

siteapp/templates/siteapp/hello.html
{% extends 'base.html' %}


{% block content %}

<style>
    body {
      background-color: #F7FCFE;
    }

    h1 {
        margin: 10rem auto;
        text-align: left;
        font-size: 10vw;
    }

    img{
        width: 100%; 
        border-radius: 1rem; 
        margin-bottom: 10rem;
    }
</style>

<div>
    <div>
        <h1>
            인사말
        </h1>

        <img src="https://museum.sunmoon.ac.kr/images/subpage/greeting.jpg" alt="">
    </div>
</div>

{% endblock %}

siteapp/templates/siteapp/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
    body {
      background-color: #F7FCFE;
    }
</style>

<body>
  <main>
      <!-- <svg width="0" height="0" version="1.1" xmlns="http://www.w3.org/2000/svg">
        
      </svg> -->
      
    <svg viewBox="0 0 75 30">
      <defs>
        <linearGradient id="Gradient1" x1="0" x2="0" y1="0" y2="1">
          <stop class="stop1" offset="0%"/>
          <stop class="stop2" offset="50%"/>
          <stop class="stop3" offset="100%"/>
        </linearGradient>

        <style type="text/css"><![CDATA[
        #rect1 { fill: url(#Gradient1); }
          .stop1 { stop-color: white; }
          .stop2 { stop-color: white; }
          .stop3 { stop-color: #c72a58; }
        ]]></style>

        <linearGradient id="Gradient2" x1="0" x2="0" y1="0" y2="1">
          <stop offset="0%" stop-color="white"/>
          <stop offset="50%" stop-color="#3b858c" stop-opacity="0"/>
          <stop offset="100%" stop-color="#3b858c"/>
        </linearGradient>


    </defs>
      <circle cx="7" cy="15" r="5" fill="#c72a58" opacity="0.1"/>
      <text x="7" y="18" font-size="5">선문대학교</text>
      <rect id="rect1" width="20" height="25" x="55" y="-30" rx="3" ry="3" transform="rotate(20)"></rect>
      <rect width="20" height="25" x="50" y="-35" rx="3" ry="3" transform="rotate(20)" fill="url(#Gradient2)"></rect>
      <text x="7" y="23" font-size="5" fill="#c72a58">박물관</text>
    </svg>

    <svg viewBox="0 0 80 50">
      <circle cx="20" cy="10" r="5" fill="#c72a58" opacity="0.1"/>
      <rect width="50" height="30" x="50" y="0" rx="3" ry="3" transform="rotate(10)" fill="#3b858c" opacity="0.1"></rect>
      <rect width="50" height="30" x="10" y="0" rx="3" ry="3" transform="rotate(20)" fill="#3b858c" opacity="0.1"></rect>
      <a xlink:href="{% url 'curatorapp:permanent_list' %}">
        <rect width="20" height="25" fill="#ffffff" x="5" y="20" rx="3" ry="3" stroke="gray" stroke-width="0.1" />
        <image xlink:href="{% static 'SMMuseum/img/sang.png' %}" x="7.5" y="23" style="width: 15;"></image>
        <text x="9.2" y="42" font-size="2.5">상설전시실</text>
      </a>
      <a xlink:href="{% url 'curatorapp:bible_list' %}">
        <rect width="20" height="25" fill="#ffffff" x="30" y="20" rx="3" ry="3" stroke="gray" stroke-width="0.1" />
        <image xlink:href="{% static 'SMMuseum/img/sung.png' %}" x="32.5" y="23" style="width:15;"></image>
        <text x="34.2" y="42" font-size="2.5">성서전시실</text>
      </a>
      <a xlink:href="{% url 'curatorapp:special_list' %}">
        <rect width="20" height="25" fill="#ffffff" x="55" y="20" rx="3" ry="3" stroke="gray" stroke-width="0.1" />
        <image xlink:href="{% static 'SMMuseum/img/tk.png' %}" x="57.5" y="23" style="width: 15;"></image>
        <text x="59.2" y="42" font-size="2.5">특별전시실</text>
      </a>
      
    </svg>
    <svg viewBox="0 0 75 70">
      <circle cx="0" cy="15" r="14" fill="#c72a58" opacity="0.1"/>
      <rect width="50" height="30" x="-50" y="-60" rx="3" ry="3" transform="rotate(150)" fill="#3b858c" opacity="0.1"></rect>
      <image xlink:href="{% static 'SMMuseum/img/btfly.png' %}" x="45" y="20" style="width: 30; border: 3px solid black"></image>
      <text x="15" y="38" font-size="5">정진철 군접도</text>
      <text x="20" y="42" font-size="2">여러가지 무늬의 오색 나비가</text>
      <text x="26" y="44" font-size="2">바위와 꽃과 어울어짐</text>
    </svg>


  </main>
</body>

{% endblock %}

templates/header.html
<style>
  header {
    position: fixed;
    top: 0;
    left: 0;
    height: 130px;
    width: 100%;
    background-color: #F7FCFE;
  }
</style>

<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #F7FCFE;">
    <a class="navbar-brand" href="{% url 'siteapp:main' %}" style="font-size: 6vw;">선문대학교</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="transform: scale(2.2);">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!-- 소개 -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" style="font-size: 4.5vw;">
            소개
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'siteapp:hello' %}" style="font-size: 3vw;">인사말</a>
            <a class="dropdown-item" href="{% url 'siteapp:history' %}" style="font-size: 3vw;">연혁</a>
            <a class="dropdown-item" href="{% url 'siteapp:group' %}" style="font-size: 3vw;">조직도</a>
            <a class="dropdown-item" href="{% url 'siteapp:route' %}" style="font-size: 3vw;">찾아오시는 길</a>
          </div>
        </li>
        <!-- 안내 -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false" style="font-size: 4.5vw;">
            안내
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'siteapp:guide_watch' %}" style="font-size: 3vw;">관람</a>
            <a class="dropdown-item" href="{% url 'siteapp:guide_facility' %}" style="font-size: 3vw;">시설</a>
            <a class="dropdown-item" href="{% url 'siteapp:guide_donation' %}" style="font-size: 3vw;">기증</a>
          </div>
        </li>
        <!-- 커뮤니티 -->
        <li class="nav-item">
          <a class="nav-link active" aria-current="page"
            href="https://museum.sunmoon.ac.kr/html/community/community01.asp" target="_blank"
            style="font-size: 4.5vw;">커뮤니티</a>
          <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">박물관소식</a>
                        <a class="dropdown-item" href="#">관람후기</a>
                        <a class="dropdown-item" href="#">Q&A</a>
                    </div> -->
        </li>

      </ul>
    </div>
  </nav>
  <hr>
</header>

templates/snippets/pagination_bible.html
<div style="text-align: center; margin: 1rem 0;">
    {% if page_obj.has_previous %}
    <a href="{% url 'curatorapp:bible_list' %}?page={{ page_obj.previous_page_number }}" 
    class="btn btn-secondary rounded-pill">
        {{ page_obj.previous_page_number }}
    </a>
    {% endif %}
    <a href="{% url 'curatorapp:bible_list' %}?page={{ page_obj.number }}"
    class="btn btn-secondary rounded-pill active">
        {{ page_obj.number }}
    </a>
    {% if page_obj.has_next %}
    <a href="{% url 'curatorapp:bible_list' %}?page={{ page_obj.next_page_number }}"
    class="btn btn-secondary rounded-pill">
        {{ page_obj.next_page_number }}
    </a>
    {% endif %}
</div>

templates/snippets/pagination_permanent.html
<div style="text-align: center; margin: 1rem 0;">
    {% if page_obj.has_previous %}
    <a href="{% url 'curatorapp:permanent_list' %}?page={{ page_obj.previous_page_number }}" 
    class="btn btn-secondary rounded-pill">
        {{ page_obj.previous_page_number }}
    </a>
    {% endif %}
    <a href="{% url 'curatorapp:permanent_list' %}?page={{ page_obj.number }}"
    class="btn btn-secondary rounded-pill active">
        {{ page_obj.number }}
    </a>
    {% if page_obj.has_next %}
    <a href="{% url 'curatorapp:permanent_list' %}?page={{ page_obj.next_page_number }}"
    class="btn btn-secondary rounded-pill">
        {{ page_obj.next_page_number }}
    </a>
    {% endif %}
</div>

templates/snippets/pagination_special.html
<div style="text-align: center; margin: 1rem 0;">
    {% if page_obj.has_previous %}
    <a href="{% url 'curatorapp:special_list' %}?page={{ page_obj.previous_page_number }}" 
    class="btn btn-secondary rounded-pill">
        {{ page_obj.previous_page_number }}
    </a>
    {% endif %}
    <a href="{% url 'curatorapp:special_list' %}?page={{ page_obj.number }}"
    class="btn btn-secondary rounded-pill active">
        {{ page_obj.number }}
    </a>
    {% if page_obj.has_next %}
    <a href="{% url 'curatorapp:special_list' %}?page={{ page_obj.next_page_number }}"
    class="btn btn-secondary rounded-pill">
        {{ page_obj.next_page_number }}
    </a>
    {% endif %}
</div>

testapp/templates/testapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center;">
        <div>
            <h1>OCR TEST</h1>
        </div>
        <form action="{% url 'testapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

testapp/templates/testapp/detail.html
<div>
    <div style="text-align: center; margin: 4rem auto;">
        <div>  
            <h2> {{ target_info.title }} </h2>
            <img src="{{ target_info.image.url }}" alt="" style="height: 12rem; width: 12rem;">
        </div>
        <div style="margin: 2rem;">
            <a href="{% url 'testapp:create' %}">
                again
            </a>
        </div>
    </div>
</div>